## YAML Template.
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/world-restaurants
        username: postgres
        password: root
            
    jpa:
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update

